version: "2.1"
services:

  virtuallabs-server-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - virtuallabs-database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://virtuallabs-database:3306/virtualLabs

  virtuallabs-client-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - virtuallabs-server-backend

  virtuallabs-database:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
        - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: root
      MYSQL_DATABASE: virtualLabs
  