mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root

    MYSQL_PASSWORD: pwd
    MYSQL_DATABASE: virtualLabs
  volumes:
    - ./data:/docker-entrypoint-initdb.d