INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (22, '25', true, 'RIVISTO', '2020-11-03 11:54:17.397', 28, 's2');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (23, '-1', false, 'CONSEGNATO', '2020-11-05 11:03:24.185', 28, 's3');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (24, '-1', false, 'NULL', '/', 28, 's4');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (25, '-1', false, 'NULL', '/', 28, 's6');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (26, '-1', false, 'NULL', '/', 28, 's7');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (27, '-1', false, 'NULL', '/', 28, 's8');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (45, '-1', false, 'NULL', '/', 51, 's2');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (46, '-1', false, 'NULL', '/', 51, 's3');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (47, '-1', false, 'NULL', '/', 51, 's4');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (48, '-1', false, 'NULL', '/', 51, 's6');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (49, '-1', false, 'NULL', '/', 51, 's7');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (50, '-1', false, 'NULL', '/', 51, 's8');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (66, '-1', false, 'NULL', '/', 72, 's2');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (67, '-1', false, 'NULL', '/', 72, 's3');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (68, '-1', false, 'NULL', '/', 72, 's4');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (69, '-1', false, 'NULL', '/', 72, 's6');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (70, '-1', false, 'NULL', '/', 72, 's7');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (71, '-1', false, 'NULL', '/', 72, 's8');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (75, '-1', false, 'NULL', '/', 81, 's2');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (76, '-1', false, 'NULL', '/', 81, 's3');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (77, '-1', false, 'NULL', '/', 81, 's4');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (78, '-1', false, 'NULL', '/', 81, 's6');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (79, '-1', false, 'NULL', '/', 81, 's7');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (80, '-1', false, 'NULL', '/', 81, 's8');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (84, '-1', false, 'NULL', '/', 90, 's2');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (85, '-1', false, 'NULL', '/', 90, 's3');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (86, '-1', false, 'NULL', '/', 90, 's4');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (87, '-1', false, 'NULL', '/', 90, 's6');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (88, '-1', false, 'NULL', '/', 90, 's7');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (89, '-1', false, 'NULL', '/', 90, 's8');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (98, '24', true, 'RIVISTO', '2020-11-03 12:01:18.743', 28, 's1');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (99, '-1', false, 'CONSEGNATO', '2020-11-05 09:40:11.791', 51, 's1');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (100, '-1', false, 'NULL', '/', 72, 's1');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (101, '-1', false, 'NULL', '/', 81, 's1');
INSERT INTO virtualLabs.homework (id, grade, permanent, status, timestamp, assignment_id, student_id) VALUES (102, '-1', false, 'NULL', '/', 90, 's1');